version: 2

jobs:
  lint:
    working_directory: ~/flow-checker
    docker:
      - image: circleci/node:8@sha256:faf0bd95bc341585a53e1f7d372e4544f98a973a76c52bc90773b5b60e5742fb
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/flow-checker
    docker:
      - image: circleci/node:8@sha256:faf0bd95bc341585a53e1f7d372e4544f98a973a76c52bc90773b5b60e5742fb
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run flow

  build:
    working_directory: ~/flow-checker
    docker:
      - image: circleci/node:8@sha256:faf0bd95bc341585a53e1f7d372e4544f98a973a76c52bc90773b5b60e5742fb
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - build