version: 2

jobs:
  test:
    working_directory: ~/check-flow
    docker:
      - image: circleci/node:8@sha256:d4668444df05dba3cfcedb3464106380e829630030de8132f503f6384f1d8d90
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Test
          command: yarn run test

  lint:
    working_directory: ~/check-flow
    docker:
      - image: circleci/node:8@sha256:d4668444df05dba3cfcedb3464106380e829630030de8132f503f6384f1d8d90
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/check-flow
    docker:
      - image: circleci/node:8@sha256:d4668444df05dba3cfcedb3464106380e829630030de8132f503f6384f1d8d90
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Flow
          command: yarn run flow

  build:
    working_directory: ~/check-flow
    docker:
      - image: circleci/node:8@sha256:d4668444df05dba3cfcedb3464106380e829630030de8132f503f6384f1d8d90
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - test
      - build