version: 2

jobs:
  lint:
    working_directory: ~/flow-checker
    docker:
      - image: circleci/node:8@sha256:c84625042e6ea1d9cf6a01397873b642e21d7de9a252cf75f93e68e82a847b2f
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/flow-checker
    docker:
      - image: circleci/node:8@sha256:c84625042e6ea1d9cf6a01397873b642e21d7de9a252cf75f93e68e82a847b2f
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run flow

  build:
    working_directory: ~/flow-checker
    docker:
      - image: circleci/node:8@sha256:c84625042e6ea1d9cf6a01397873b642e21d7de9a252cf75f93e68e82a847b2f
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - build